config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  resources :todos do
    member do
      post 'toggle'
    end
    collection do
      post 'destroy_all_complete'
      post 'toggle_all_complete'
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates_presence_of :title

  def self.more_to_do?
    where(is_complete: false).any?
  end

  def self.num_left_to_do
    where(is_complete: false).size
  end

  def self.anything_completed?
    where(is_complete: true).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.new
    @todos = Todo.all
  end

  def create
    @todo = Todo.create(params.require(:todo).permit(:title))
    @num_left_to_do = Todo.num_left_to_do
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    @num_left_to_do = Todo.num_left_to_do
  end

  def toggle
    @todo = Todo.find(params[:id])
    @todo.toggle!(:is_complete)
    @no_more_to_do = !Todo.more_to_do?
    @num_left_to_do = Todo.num_left_to_do
  end

  def destroy_all_complete
    complete_todos = Todo.where(is_complete: true)
    @delete_ids = complete_todos.map{|todo| todo.id}
    complete_todos.destroy_all
  end

  def toggle_all_complete
    @todos = Todo.all
    Todo.update_all is_complete: Todo.more_to_do?
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(params.require(:todo).permit(:title))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def hide_or_show_footer
    # Hide footer if no more todos are left
    if Todo.count == 0
      "$('#footer').hide();".html_safe
    else
      "$('#footer').show();".html_safe
    end
  end

  def hide_or_show_clear_completed
    # Hide destroy-complete if no todos are completed
    if !Todo.anything_completed?
      "$('#destroy-complete').hide();".html_safe
    else
      "$('#destroy-complete').show();".html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThreeDoMVC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<footer id="info">
  <p>Click to edit a todo</p>
  <p>Created by <a href="http://github.com/starspace1">Leslie Brown</a></p>
  <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>
</body>
</html>

app/views/todos/_new_todo.html.erb
<%= form_for todo, remote: true do |f| %>
  <%= f.text_field :title, id: 'new-todo', placeholder: "What needs to be done?", autofocus: true %>
<% end %>

app/views/todos/_todo.html.erb
<li id=<%= "todo_#{todo.id}" %> <%= 'class=completed' if todo.is_complete %>>
  <div class="view">
    <%= form_for todo, url: toggle_todo_path(todo), method: :post, remote: true do |f| %>
      <%= f.check_box :is_complete, class: 'toggle' %>
    <% end %>
    <a><%= todo.title %></a>
    <%= form_for todo, method: :delete, remote: true do |f| %>
      <%= f.button "", class: 'destroy' %>
    <% end %>
  </div>
  <%= form_for todo, method: :patch, remote: true do |f| %>
    <%= f.text_field :title, class: 'edit' %>
  <% end %>
</li>

app/views/todos/create.js.erb
$('<%= j(render @todo) %>').appendTo('#todo-list');

$("#new-todo").val(''); 

<%= hide_or_show_footer %>

$("#todo-count strong").html(<%= @num_left_to_do %>)

<%= hide_or_show_clear_completed %>

app/views/todos/destroy.js.erb
$('#<%= "todo_#{@todo.id}" %>').remove();

<%= hide_or_show_footer %>

$("#todo-count strong").html(<%= @num_left_to_do %>)

<%= hide_or_show_clear_completed %>

app/views/todos/destroy_all_complete.js.erb
<% @delete_ids.each do |id| %>
  $('#<%= "todo_#{id}" %>').remove();
<% end %>

<%= hide_or_show_footer %>

<%= hide_or_show_clear_completed %>

app/views/todos/index.html.erb
<!doctype html>
<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    <%= render partial: 'new_todo', locals: { todo: @todo } %>
  </header>
  <!-- This section should be hidden by default and shown when there are todos to display -->
  <section id="main">
    <form action="/todos/toggle_all_complete" method="POST" data-remote="true">
      <input id="toggle-all" type="checkbox">
      <label for="toggle-all">Mark all as complete</label>
    </form>
    <ul id="todo-list">
      <%= render @todos %>
    </ul>
  </section>
  <!-- This footer should hidden by default and shown when there are todos -->
  <footer id="footer" <%="class = hidden" if Todo.count == 0 %>>
    <span id="todo-count"><strong><%= Todo.num_left_to_do %></strong> items left</span>
    <ul id="filters">
      <li>
        <a class="selected" href="/">All</a>
      </li>
      <li>
        <a href="/active">Active</a>
      </li>
      <li>
        <a href="/completed">Completed</a>
      </li>
    </ul>
    <form id="destroy-complete" action="/todos/destroy_all_complete" method="POST" data-remote="true" <%="class = hidden" if !Todo.anything_completed? %>>
      <button id="clear-completed">Clear completed</button>
    </form>
  </footer>
</section>

app/views/todos/toggle.js.erb
this_todo = $('#<%= "todo_#{@todo.id}" %>')

<% if @todo.is_complete %>
  this_todo.addClass('completed')
<% else %>
  this_todo.removeClass('completed')
<% end %>

$('#toggle-all').prop('checked', <%= @no_more_to_do %>)

$('#todo-count strong').html(<%= @num_left_to_do %>)

<%= hide_or_show_clear_completed %>

app/views/todos/toggle_all_complete.js.erb
<% @todos.each do |todo| %>
  this_todo = $('#<%= "todo_#{todo.id}" %>')
  this_todo.find(".toggle").prop("checked", <%= todo.is_complete %>)
  
  <% if todo.is_complete %>
    this_todo.addClass("completed")
  <% else %>
    this_todo.removeClass("completed")
  <% end %>

<% end %>

$("#todo-count strong").html(<%= Todo.num_left_to_do %>)

<%= hide_or_show_footer %>

<%= hide_or_show_clear_completed %>

app/views/todos/update.js.erb
this_todo = $('#<%= "todo_#{@todo.id}" %>')
this_todo.find('a').text("<%= @todo.title %>");
this_todo.removeClass('editing');